CREATE DATABASE loja;
USE loja;

CREATE TABLE paises(
    id_pais INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(191) NOT NULL,
    ddi INT
);

CREATE TABLE estados(
    id_estado INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(191) NOT NULL,
    sigla CHAR (2),
    pais_id INT UNSIGNED NOT NULL
);

CREATE TABLE cidades(
    id_cidade INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(191),
    estado_id INT UNSIGNED
);

SHOW TABLES;